blog/urls.py
from django.conf.urls import url
from .views import (
    index_view,
    post_list,
    post_create,
    post_detail,
    post_delete,
    post_update,
)

urlpatterns = [
    url(r'^$', post_list),
    url(r'^list/', post_list, name='list'),
    url(r'^create/', post_create, name='create'),
    # d+ means that it will only accept digits
    url(r'^(?P<pk>\d+)/$', post_detail, name='detail'),
    url(r'^(?P<pk>\d+)/edit/$', post_update, name='update'),
    url(r'^delete/', post_delete, name='delete'),
]

cms/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from blog import urls as blog_urls

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^posts/', include(blog_urls, namespace='posts')),
    # url(r'^', include(blog_urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models.signals import pre_save

from django.utils.text import slugify

# Create your models here.


def upload_location(instance, filename):
    return "%s/%s" % (instance.id, filename)


class Post(models.Model):
    title = models.CharField(max_length=50)
    slug = models.SlugField(unique=True)
    image = models.ImageField(upload_to=upload_location,
                              null=True, blank=True,
                              height_field="height_field",
                              width_field="width_field")
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    content = models.TextField()
    updated = models.TimeField(auto_now=True, auto_now_add=False)
    timestamp = models.TimeField(auto_now=False, auto_now_add=True)
    # auto_now updates every time it is saved

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("posts:detail", kwargs={"pk": self.id})
        # return "/posts/%s/" % self.id

    class Meta:
        ordering = ["-id", "-timestamp", "-updated"]


def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Post.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" %(slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug


def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)


pre_save.connect(pre_save_post_receiver, sender=Post)

blog/forms.py
from django import forms

from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            "title",
            "image",
            "content"
        ]

blog/views.py
# from urllib import quote

from django.contrib import messages
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Q
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404, redirect

from .forms import PostForm
from .models import Post


def index_view(request):
    context = {
        "title": "Home"
    }
    return render(request, 'post_list.html', context)


def post_create(request):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    form = PostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        messages.success(request, "Successfully created")
        return HttpResponseRedirect(instance.get_absolute_url())

    context = {
        "title": "New Post",
        "form": form
    }
    return render(request, 'post_form.html', context)


def post_detail(request, pk):
    instance = get_object_or_404(Post, id=pk)
    # share_string = quote(instance.content)
    context = {
        "title": "Detail",
        "post": instance,
        # "share_string": share_string
    }
    return render(request, 'post_detail.html', context)


def post_list(request):
    queryset_list = Post.objects.all()  # .order_by("-timestamp")
    # search query
    query = request.GET.get("q")
    if query:
        queryset_list = queryset_list.filter(
            Q(title__icontains=query) |
            Q(content__icontains=query)
        ).distinct()
    paginator = Paginator(queryset_list, 4)  # Show 4 items per page
    page_request_var = 'page'
    page = request.GET.get(page_request_var)
    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        queryset = paginator.page(1)
    except EmptyPage:
        queryset = paginator.page(paginator.num_pages)
    context = {
        "title": "List",
        "object_list": queryset,
        "page_request_var": page_request_var
    }
    return render(request, 'post_list.html', context)


def post_update(request, pk=None):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    instance = get_object_or_404(Post, id=pk)
    form = PostForm(request.POST or None, request.FILES or None, instance=instance)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        messages.success(request, "Successfully updated")
        return HttpResponseRedirect(instance.get_absolute_url())

    context = {
        "post": instance,
        "form": form,
        "title": "Update"
    }
    return render(request, 'post_form.html', context)


def post_delete(request, pk=None):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    instance = get_object_or_404(Post, id=pk)
    instance.delete()
    # context = {
    #     "title": "Delete Post"
    # }
    messages.success(request, "Successfully deleted")
    return redirect("posts:list")

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block head_title %}{{ title }}{% endblock head_title %}</title>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">

    <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>
    {% include 'navbar.html' %}
    {% include 'messages_display.html' %}
    <div class="container">
        <h1>{{ title }}</h1><br/>
        {% block content %}{% endblock %}
    </div>

<!-- Latest compiled and minified JavaScript -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>

templates/messages_display.html
{% if messages %}
        <div class="messages">
            <ul class="messages">
                {% for message in messages %}
                    <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>
                        {{ message }}
                    </li>
                {% endfor %}
            </ul>
        </div>
{% endif %}

templates/navbar.html
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">jay.r3d</a>
        </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="active"><a href="{% url 'posts:list' %}">Home <span class="sr-only">(current)</span></a></li>
{#                <li><a href="admin/">Admin</a></li>#}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                        aria-expanded="false">Posts <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'posts:create' %}">New Post</a></li>
{#                        <li><a href="{% url 'posts:update' %}">Edit Post</a></li>#}
                        <li><a href="{% url 'posts:delete' %}">Delete Post</a></li>
                    </ul>
                </li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

templates/post_detail.html
{% extends 'base.html' %}

{% block head_title %}
    {{ post.title }} | {{ block.super }}
{% endblock head_title %}

<div class="col-sm-6 col-sm-offset-3">
    {% block content %}
    {{ title }}<br/>
        {{ post.id }}<br/>
        {{ post.title }}<br/>
        {% if post.image %}
            <img src="{{ post.image.url }}" alt="{{ post.title }} avatar" class="img-responsive">
        {% endif %}
        <br/>
        {{ post.content| linebreaks }}<br/>

        {{ request.build_absolute_uri }}

        <a href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}">Share on Facebook</a>

        <a href="https://twitter.com/home?status={{ share_string }}%20{{ request.build_absolute_uri }}">
            Share on Twitter
            </a>

        <a href="https://www.linkedin.com/shareArticle?mini=true&url={{ request.build_absolute_uri }}&title
        ={{ share_string }}%20me!&source={{ request.build_absolute_uri }}">
        Share on Linkedin
        </a>
    {% endblock %}
</div>

templates/post_form.html
{% extends 'base.html' %}
{% block content %}
    <form method="post" action="" enctype="multipart/form-data">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Create Post" />
    </form>
{% endblock %}

templates/post_list.html
{% extends 'base.html' %}
{% block content %}
    <div class="row">
        <form method="get" action="">
            <input type="text" name="q" placeholder="Search Posts" value="{{ request.GET.q }}">
            <input type="submit" value="Submit" class="btn btn-primary">
        </form>
        {% for obj in object_list %}
            <div class="col-sm-6 col-md-4">
                <div class="thumbnail">
                    {% if obj.image %}
                        <img src="{{ obj.image.url }}" alt="{{ post.title }} avatar" class="img-responsive">
                    {% endif %}
                    <div class="caption">
                        <h3><a href="{{ obj.get_absolute_url }}">{{ obj.title }}</a> <small
                        >{{ obj.timestamp| time }}</small></h3>
                        <p>{{ obj.content| linebreaks| truncatechars:100 }}</p>
                        <p>
                            <a href="{{ obj.get_absolute_url }}" class="btn btn-primary" role="button">View</a>
                        </p>
                    </div>
                </div>
            </div>

            {% cycle "" "<div class='col-sm-12'><hr/></div></div><div class='row'>" %}
        {% endfor %}

    <div class="pagination">
        <span class="step-links">
            {% if object_list.has_previous %}
                <a href="?{{ page_request_var }}={{ object_list.previous_page_number }}{% if request.GET.q %}&q
                ={{ request.GET.q }}{% endif %}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
            </span>

            {% if object_list.has_next %}
                <a href="?{{ page_request_var }}={{ object_list.next_page_number }}{% if request.GET.q %}&q
                ={{ request.GET.q }}{% endif %}">next</a>
            {% endif %}
        </span>
    </div>
    </div>
{% endblock %}